[parity]
chain = "desafiochain.json"
base_path = "/tmp/desafio1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
port = 8181
[websockets]
port = 8451
[ipc]
disable = true
#[account]
#password = ["node.pwds"]
#[mining]
#engine_signer = "address1"
#reseal_on_txs = "none"
